### ISSUE TITLE
Bug : 남은 문제들

### ISSUE THREAD

**Issue by yjlee9909** [RainbowMarkets/RainbowMarket#164]
## :rainbow: Description
- 배포 후 학인되는 문제들 입니다.

## :rainbow: To do
- [x] 하단 네비에 포스트 글들이 가려짐
- [x] UserList 앵커들 글자 색이 Color76으로 덮혀짐
- [x] 포스트 사진 이미지가 cover로 돼있어 잘리는 부분이 생김

## :rainbow: Due Date
- ~ 2023.02

## :rainbow: ETC
- 기타사항

**Comment by Skylark92** [comment]
하단 네비 position을 sticky로 돌리면 해결, 하지만 배포 후에 모바일 환경에서 주소창에 가려질지 확인 필요함. 또한 이렇게 적용하면 프로필 화면 게시글 피드 가장 아래에 알 수 없는 여백 존재함.

**Comment by DADA6041** [comment]
app.js main에 padding 을 주거나 하는 방법으로 해결 가능!

**Comment by Skylark92** [comment]
GlobalStyle.js에서 Main에 padding-bottom: 60px; 추가.

**Comment by Skylark92** [comment]
글로벌스타일에 적용했던 &:focus, &:hover, &:visited, &:link, &:active color 속성들을 로그인모달 스타일로 이동함.
