### ISSUE TITLE
[Fix] PostContent 내 이미지 에러 처리

### ISSUE THREAD

**Issue by Skylark92** [RainbowMarkets/RainbowMarket#170]
## :rainbow: Description
- 이미지 주소 : "https://mandarin.api.weniv.co.kr/undefined" 해당 이미지 에러 처리 안 됨.

## :rainbow: To do
- [x] PostContent 내 이미지 에러 처리

## :rainbow: Due Date
- 2022.01.31

## :rainbow: ETC
- 임시로 이미지를 주소에 따라 구분하여 처리하도록 해놨기 때문에 발생한 것으로 예상함. 다른 곳에서 처럼 이미지 에러 처리를 하도록 하겠습니다.

**Comment by yjlee9909** [comment]
늦었지만 확인했습니다~!
