### ISSUE TITLE
[Bug] 없는 게시물 id에 접근하면 로딩화면만 보여주는 현상

### ISSUE THREAD

**Issue by Skylark92** [RainbowMarkets/RainbowMarket#172]
## :rainbow: Description
- 로그인을 하지 않은 채로, 앱주소/post/없는 게시글 id (예, 1324_432)에 접근하면 데이터를 받아오는데 실패하고 아무런 조치가 없어 로딩화면만 보이는 현상

## :rainbow: To do
- [ ] 예외 처리로 사용자 경험 높이기

## :rainbow: Due Date
- 2023.02

## :rainbow: ETC
- 로그인을 하지 않았을 때(토큰이 없을 때) 로그인할 수 있도록 홈화면으로 이동시키거나, 혹은 데이터 불러오기에 실패했을 때 404 페이지를 보여주는 식의 처리가 필요하다고 보임.

**Comment by yjlee9909** [comment]
둘러보기 기능이 아닌 그저 로그인 안한 상태에서 url 변경했을 경우에 말씀하시는거죠? 
버그 내용 확인했습니다!
