### ISSUE TITLE
[Enhance] 이미지 업로드 시 용량 줄이기

### ISSUE THREAD

**Issue by Skylark92** [RainbowMarkets/RainbowMarket#174]
## :rainbow: Description
- 이미지 업로드 시에 이미지 용량을 줄여, 서버 부하를 줄이고 불러오는 속도 또한 향상 시킬 예정입니다.

## :rainbow: To do
- [ ] browser-image-compression 라이브러리 사용하여 이미지 업로드 시 이미지 압축

## :rainbow: Due Date
- 2023.02.01

## :rainbow: ETC
- 성능 점수 개선해봅시다~!

**Comment by yjlee9909** [comment]
개선 가보자고~~ 🫡
