### ISSUE TITLE
🚨 🎉 메리 크리스마스!! 푹 쉬기!! 잘 놀기!! 🎉🚨 

### ISSUE THREAD

**Issue by Skylark92** [RainbowMarkets/RainbowMarket#92]
기한 12월 26일까지 동면

**Comment by yjlee9909** [comment]
. へ(^o^)へ　허잇짜!
　　|へ
　　/

　＜(　^o^)／　요잇짜!
　　／　　＞

　(／^o^)／　호잇짜!
　＜　　＼

댄스댄스! ! !
　＜(　^o^)＞
　　三)　　)三
　　＜￣￣＞

**Comment by DADA6041** [comment]
◌ ｡˚✩(  ›   ̫ ‹ )✩˚ ｡◌
행복한클스마스~!
